name: 'water'
max_iter: 100
tolerance: 5e-4
include_second_order_constraints: False
position_idx: [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
velocity_idx: [ 9,10,11,12,13,14,15,16,17 ]
length: [ 0.957, 1.513, 0.957 ]
scale: ???