defaults:
  - constraint: imagedenoising
  - minimization: multibodypendulum
  - data: imagedenoising
  - model: resnet
  - logging: standard

data:
  n_train: 100
  n_val: 100

run:
  experiment_name: 'imagedenoising'
  name: ???
  epochs: 1
  debug: false
  seed: 1234
  loss_type: 'mse'
  precision: torch.float64
  device: ???
  #  loss_indices: ${data.data_id}
  loss_indices: { 'r': [ 0, 1 ] }

optimizer:
  lr: 0.001

model:
  con_type: 'low'
  penalty_strength: 0
  regularization_strength: 0.1

#To see the results use: mlflow ui --backend-store-uri /home/tue/PycharmProjects/results/mlflow (where path can be found in the logging yaml)