model_mim:
  dim_in: ???
  dim_latent: 120
  layers: 8
  max_radius: 15
  discretization_method: 'rk4'
  orthogonal_projection: True
  penalty_strength: 1
  regularization_strength: 1

model_eq:
  irreps_inout: "6x1o"
  irreps_hidden: "30x0o+30x0e+20x1o+20x1e"
  layers: 8
  max_radius: 15
  number_of_basis: 8
  embed_dim: 2
  max_atom_types: 20
  radial_neurons: [48]
  num_neighbors: -1
  penalty_strength: 1
  regularization_strength: 1
