defaults:
  - constraint: multibodypendulum
  - data: multibodypendulum
  - model: mimetic
  - logging: standard
  - override hydra/sweeper: optuna
#  - override hydra/sweeper/sampler: tpe
  - override hydra/sweeper/sampler: grid


hydra:
  mode: MULTIRUN
  sweeper:
    sampler:
      seed: ${run.seed}
    direction: minimize
    study_name: simple_objective
    storage: null
    n_trials: 10
    n_jobs: 1
    params:
      model.penalty_strength: range(1,20,1)
#      model.penalty_strength2: range(1,20,1)
#      horse: range(1,10,1)



run:
  experiment_name: 'Penalty_tuning, nskip=100'
  name: ???
  epochs: 50
  debug: false
  seed: 1234
  loss_type: 'eq'
  precision: torch.float64
  device: ???
  loss_indices: ${data.data_id}

optimizer:
  lr: 0.001
#  momentum: 0.9

data:
  nskip: 100
  n_train: 1000

model:
  con_type: ''
  penalty_strength: 10
  regularization_strength: 0