
defaults:
  - constraint: multibodypendulum
  - data: multibodypendulum
  - model: mimetic
  - logging: standard

hydra:
  mode: MULTIRUN
  sweep:
    dir: ${logging.hydra_folder}
  sweeper:
    params:
#      +constraints.type: ['','high','low']



run:
  experiment_name: 'tmp'
  name: ???
  epochs: 10
  debug: false
  seed: 1234
  loss_type: 'eq'
  precision: torch.float64
  device: ???
  loss_indices: ${data.data_id}
  epoch_start: 0

optimizer:
  lr: 0.001
#  momentum: 0.9

data:
  nskip: 200

model:
  con_type: 'high'
  penalty_strength: 10
  regularization_strength: 0
#  load_state: '/home/tue/PycharmProjects/results/mlflow/908215842034787892/2301e71e82bb438a92192b22e576d888/artifacts/models/state_dict.pth'