defaults:
  - constraint: multibodypendulum
  - data: multibodypendulum
  - model: mimetic
  - logging: standard

hydra:
  mode: MULTIRUN
  sweep:
    dir: ${logging.hydra_folder}
  sweeper:
    params:
      ++model.penalty_strength: 0,1,5,10,50,100
      ++model.regularization_strength: 0,1,5,10
#      +model: "{con_type : '', penalty_strength : 3, regularization_strength : 0},{con_type : '', penalty_strength : 0, regularization_strength : 3},{con_type : 'low', penalty_strength : 3, regularization_strength : 3},{con_type : 'high', penalty_strength : 3, regularization_strength : 3}"
#      ++run.seed: 1234,1235,1236
#      +model: "{con_type : 'high', penalty_strength : 3, regularization_strength : 3}"
#      ++run.seed: 1234,1235,1236


data:
  n_train: 100
  n_val: 100
  nskip: 200

run:
  experiment_name: 'mbp - Penalty sweep nskip200'
  name: ???
  epochs: 50
  debug: false
  seed: 1234
  loss_type: 'eq'
  precision: torch.float64
  device: ???
  loss_indices: ${data.data_id}

optimizer:
  lr: 0.001
#  momentum: 0.9

model:
  con_type: ''
  penalty_strength: 100
  regularization_strength: 5

#To see the results use: mlflow ui --backend-store-uri /home/tue/PycharmProjects/results/mlflow (where path can be found in the logging yaml






#defaults:
#  - constraint: multibodypendulum
#  - data: multibodypendulum
#  - model: mimetic
#  - logging: standard
##  - override hydra/sweeper: optuna
##  - override hydra/sweeper/sampler: tpe
##  - override hydra/sweeper/sampler: grid
#
#
#hydra:
#  mode: MULTIRUN
#  sweep:
#    dir: ${logging.hydra_folder}
#  sweeper:
#    params:
#      ++model.penalty_strength: 1,3,5,7,10,15
#
##      +constraints.type: ['','high','low']
#
#
#
#run:
#  experiment_name: 'Penalty_tuning, nskip=100'
#  name: ???
#  epochs: 50
#  debug: false
#  seed: 1234
#  loss_type: 'eq'
#  precision: torch.float64
#  device: ???
#  loss_indices: ${data.data_id}
#
#optimizer:
#  lr: 0.001
##  momentum: 0.9
#
#data:
#  nskip: 100
#  n_train: 1000
#
#model:
#  con_type: ''
#  penalty_strength: 10
#  regularization_strength: 0