defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: ${run.seed}
    direction: minimize
    study_name: simple_objective
    storage: null
    n_trials: 20
    n_jobs: 1

    params:
      optimizer.lr: range(0.001,0.01,0.001)

run:
  epochs: 3
  debug: false
  seed: 1234
  model_type: 'mim'
  loss_type: 'eq'
  precision: torch.float64
  device: ???
  loss_indices: ???

data:
  type: 'multibodypendulum'
  file: './../data/multibodypendulum/multibodypendulum.npz'
  use_val: False
  use_test: False
  metafile: ???
  n_train: 100
  n_val: 100
  n_test: 100
  batchsize: 10
  nskip: 200
  device: ???
  rscale: 1
  vscale: 1
  data_id: {'r':[0,1], 'v':[2,3]}

constraints:
  name: 'multibodypendulum'
  type: 'high'
  max_iter: 200
  tolerance: 1e-4
  include_second_order_constraints: False
  regularization: 1


optimizer:
  lr: 0.001
  momentum: 0.9

model:
