defaults:
  - constraint: water
  - data: water
  - model: equivariant
  - logging: standard

hydra:
  mode: MULTIRUN
  sweep:
    dir: ${logging.hydra_folder}
  sweeper:
    params:
      +model: "{con_type : '', penalty_strength : 0, regularization_strength : 1},{con_type : 'low', penalty_strength : 1, regularization_strength : 1},{con_type : 'high', penalty_strength : 1, regularization_strength : 1},{con_type : '', penalty_strength : 1, regularization_strength : 0}"
      ++run.seed: 1234,1235,1236


data:
  n_train: 10000
  n_val: 10000
  nskip: 50

run:
  experiment_name: 'water - tables ntrain=10000'
  name: ???
  epochs: 30
  debug: false
  seed: 1234
  loss_type: 'eq'
  precision: torch.float64
  device: ???
  loss_indices: { 'r': [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ] }
#  loss_indices: ${data.data_id}

optimizer:
  lr: 0.001

model:
  con_type: ''
  penalty_strength: 0
  regularization_strength: 1

#To see the results use: mlflow ui --backend-store-uri /home/tue/PycharmProjects/results/mlflow (where path can be found in the logging yaml)